### ISSUE TITLE
Possible to have various categories to be rated 1 to 5?

### ISSUE THREAD

**Issue by RetroGameTalk** [pryley/site-reviews#1]
Hello, i'm looking for a plugin where users can review posts with 5 game categories Like:
Graphics, Gameplay, Music, Replayability etc. 
Does this plugin allow more than one 5 stars rating or just the single general one?

Thanks!

**Comment by pryley** [comment]
Just the one.

Please submit questions about the plugin on the [WordPress support forum](https://wordpress.org/support/plugin/site-reviews/), the github repository is **only** for development.

Thanks
