### ISSUE TITLE
No styling and some settings does not work

### ISSUE THREAD

**Issue by hexclann** [pryley/site-reviews#11]
Hello, I have site reviews plugin installed on my Wordpress website running Wordpress 5.5.1 and OceanWp theme. 
when I add the site reviews "submit review" short code, it appears like this:

![firefox_CnHmmEqhyZ](https://user-images.githubusercontent.com/59732888/92559201-bb9a8d00-f28d-11ea-89a6-1ac31f4f051e.png)

The stars are not visible, submit button is not visible. I have tried all the plugin styles available in the settings (while clearing cache every time) but it does not work. Can you please help me?

Edit: I also disabled the Terms in the settings but it still appears in the form

**Comment by pryley** [comment]
Please see: https://wordpress.org/support/topic/my-stars-are-not-showing/#post-12220906

If that does not solve it, please create a topic on the [WordPress Support Forum](http://wordpress.org/support/plugin/site-reviews/).
