### ISSUE TITLE
Filter for using custom taxonomy instead of 'site-review-category'

### ISSUE THREAD

**Issue by toffebjorkskog** [pryley/site-reviews#12]
It would be nice if there was a filter that would enable you to swap out
[const TAXONOMY = 'site-review-category';](https://github.com/pryley/site-reviews/blob/ad4bd953ddcd66c4582e03385cc1aacf8d090f22/plugin/Application.php#L26)
for something else.

**Comment by pryley** [comment]
What reason do you have to change the taxonomy name?
