### ISSUE TITLE
Issue with assets path in local development

### ISSUE THREAD

**Issue by jnasoy** [pryley/site-reviews#14]
I am currently using the latest version of the plugin.

The assets path is broken in local development.

I am using Local by Flywheel in Windows 10 OS.
Previous version of the plugin was working in my setup.

![image](https://user-images.githubusercontent.com/7227288/97116941-b5784700-173b-11eb-979f-13ae91dbb93a.png)

![image](https://user-images.githubusercontent.com/7227288/97116911-68947080-173b-11eb-80dc-12df502e2130.png)

**Comment by pryley** [comment]
This is fixed in v5.1.4
