### ISSUE TITLE
'Slow query' reported by Query Monitor

### ISSUE THREAD

**Issue by colinhowells** [pryley/site-reviews#16]
Love the plugin, it was really nice to find a non-bloated, well-architected and extensible plugin handling this use case, and I appreciate your work on it.

With the v5 rollout (I didn't see this using v4) I'm now seeing [Query Monitor](https://github.com/johnbillion/query-monitor) flag a query as being slow, this is the [query generated by `tableConstraintExists()`](https://github.com/pryley/site-reviews/blob/c54c1ac689f67cddebe31b574c53a89e6588d7cc/plugin/Database/SqlSchema.php#L283):

```sql
SELECT CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = 'wordpress'
```

In case it matters, this is locally, on a multisite, within Docker. I haven't yet upgraded any production site. Just passing this on to you in case you want to check out that query and see if any optimizations can be made ...

**Comment by pryley** [comment]
I'm not sure why it's slow, I'm getting micro-seconds on a local install for this query.

What is your mySQL version and what database engine do your tables use, MyISAM or InnoDB?

![image](https://user-images.githubusercontent.com/134939/97226126-2dc12580-1799-11eb-8bd0-882c314a576a.png)

![image](https://user-images.githubusercontent.com/134939/97228297-51d23600-179c-11eb-9f72-bc8f72ea97aa.png)

**Comment by pryley** [comment]
See also:

https://wordpress.org/support/topic/limit-reviews/#post-13578282

**Comment by pryley** [comment]
Site Reviews checks for the custom database tables and table constraints on every page load, these checks should only take a few micro seconds to perform. I may change this to an option in the database that stores the tables status. My concern however, is when someone manually deletes the tables thinking they are cleaning the database, and then the website breaks.

**Comment by pryley** [comment]
@colinhowells I just noticed you are using a multisite.

Please make sure you perform some tests locally as there has been a [report of an issue](https://wordpress.org/support/topic/update-breaks-login/) with Site Reviews v5 on a multisite (particularly when the plugin is network activated). 

I have been unable to replicate this issue myself, but I am working on an update to provide better multisite compatibility.

**Comment by colinhowells** [comment]
Let's see ... MySQL 5.7, InnoDB. This is multisite – network activation or just activating on a single site has the same effect, no problems other than this reported slowness (which obviously isn't even noticeable to the visitor, only to QM).  

It might just be due to my local dev setup, WP in Docker generally can get weird (some local-dev apps wrapping Docker I find unusable). 

I was holding off upgrading to v5 in production just in case this was going to get addressed; but if you're not concerned, I'm not concerned – I was just curious if i'd run into some edge case that'd be useful for you to know about. When I do upgrade in production I'll let you know how that went.

Here's some screenshots – note I have a custom DB prefix:

![image](https://user-images.githubusercontent.com/2035314/97231291-8643f300-1798-11eb-9807-34c1ad8661db.png)

![image](https://user-images.githubusercontent.com/2035314/97231628-fa7e9680-1798-11eb-9c3c-c717b9fbec1c.png)

**Comment by colinhowells** [comment]
Also – I'd think storing the DB status in an autoloaded option'd be fine: firstly, if you're deleting DB tables you're already asking for trouble without first checking what is what, and secondly the plugin is kinda 'for WP devs'; you're already assuming people are going to get more involved than checking options in a UI.

**Comment by pryley** [comment]
I recently had a problem with Woocommerce. After deleting the plugin I removed the tables it creates, including the actionscheduler tables.

![image](https://user-images.githubusercontent.com/134939/97233106-00c64000-17a4-11eb-8efa-6661ce32682e.png)

When I installed Woocommerce again a few weeks later, it brought the site down because those tables no longer existed and they don't check for it on activation.

I can probably also just perform the check on plugin activation however.

**Comment by colinhowells** [comment]
Ah, yeah, I can see why you built in that check, that makes perfect sense – don't feel compelled to change what you're doing just for me; you've dealt with a lot more of these things than I have.

**Comment by pryley** [comment]
Also, [register_activation_hook](http://developer.wordpress.org/reference/functions/register_activation_hook/) does not fire when a plugin is updated but only when it's first activated. I think I will leave this for now but can always revisit in the future.

**Comment by pryley** [comment]
This will be optimised in v5.2. Instead of verifying the tables on each page load, it will simply check for the existence of an option key instead.

**Comment by colinhowells** [comment]
Just for kicks I looked around to see how most people deal with this, and ran across [using `get_var()` to check](https://wordpress.stackexchange.com/questions/11641/checking-if-database-table-exists); this is [also what `maybe_create_table()` does](https://developer.wordpress.org/reference/functions/maybe_create_table/) – I'm not sure how _this_ would be more performant than what you're already doing, though

**Comment by pryley** [comment]
I'm using `get_col()` instead of `get_var()` as the "table exists" check runs for each of the four custom tables and this way I can just do a single query for the existence of each of the four tables instead of running a query for each one.

https://github.com/pryley/site-reviews/blob/04218428131eb1a1c993b2ad0e347cc8cce977ca/plugin/Database/SqlSchema.php#L282-L294

It should take less than a millisecond to run.

**Comment by colinhowells** [comment]
Right, hence me saying 'not sure how this would be more performant than what you're already doing' – like you say the option check'll be much quicker, if a little more dangerous. Thanks for having a little conversation about it, I only rarely deal with custom tables so I was curious what the common practice was

**Comment by pryley** [comment]
I'm learning about all of this too, particularly how custom tables work with Multisite.

What I've opted to do is perform the tableExists check on plugin activation, and a check for the option key on page load (which will run the table checks again if it does not exist). I think this is fairly safe to do and more performant, as if they deleted the tables but not the option, a simple plugin deactivation (or manually deleting the plugin and reinstalling) and then activating it again will fix everything.

**Comment by pryley** [comment]
If you're interested how Site Reviews creates the custom tables and works with Multisite installs, see:

https://github.com/pryley/site-reviews/blob/develop/plugin/Install.php
https://github.com/pryley/site-reviews/blob/develop/plugin/Database/SqlSchema.php

**Comment by colinhowells** [comment]
I'll have a look, thanks! I don't know if you're hip to the [Berlin ORMish project](https://github.com/berlindb/core), I just remembered it now

**Comment by pryley** [comment]
Looks interesting, thanks. 

I have some fairly strict coding guidelines that I follow, like maximum class and method size/complexity, etc., but I'll take a look through it at some point and maybe combine some the concepts into my database implementation if needed.

**Comment by colinhowells** [comment]
Yeah, that's as close to official as can be, given that [Jacoby's doing it](https://wordpress.tv/2019/08/28/john-jacoby-advanced-database-management-for-plugins/)
