### ISSUE TITLE
Error activating plugin

### ISSUE THREAD

**Issue by robwilc** [pryley/site-reviews#17]
I've just updated the plugin to 5.1.6, and when I try to activate the plugin I get an error:

Fatal error: Uncaught Error: Call to undefined function GeminiLabs\SiteReviews\Helpers\mb_strtolower() in /var/www/rachel/wp-content/plugins/site-reviews/plugin/Helpers/Str.php:252 Stack trace: #0 /var/www/rachel/wp-content/plugins/site-reviews/plugin/Helpers/Str.php(110): GeminiLabs\SiteReviews\Helpers\Str::snakeCase() #1 /var/www/rachel/wp-content/plugins/site-reviews/plugin/Database/Sql.php(282): GeminiLabs\SiteReviews\Helpers\Str::dashCase() #2 /var/www/rachel/wp-content/plugins/site-reviews/plugin/Database/Sql.php(60): GeminiLabs\SiteReviews\Database\Query->sqlHandle() #3 /var/www/rachel/wp-content/plugins/site-reviews/plugin/Database/SqlSchema.php(151): GeminiLabs\SiteReviews\Database\Query->sql() #4 /var/www/rachel/wp-content/plugins/site-reviews/plugin/Database/SqlSchema.php(226): GeminiLabs\SiteReviews\Database\SqlSchema->createAssignedPostsTable() #5 /var/www/rachel/wp-content/plugins/site-reviews/plugin/Database.php(51): GeminiLabs\SiteReviews\Database\SqlSchema->createTables() #6 /var/www/rachel/wp-content/plu in /var/www/rachel/wp-content/plugins/site-reviews/plugin/Helpers/Str.php on line 252

Is there something that I can do to help further?

**Comment by pryley** [comment]
@robwilc Would you please test the latest develop branch and tell me if it resolves the problem?

https://github.com/pryley/site-reviews/archive/develop.zip

Additional details of the fix here: https://github.com/pryley/site-reviews/commit/b461ed5f18b9424dac170186015376c61ce728f9

**Comment by robwilc** [comment]
Hi!  It works with the develop branch !
