### ISSUE TITLE
Display Pagination in list type

### ISSUE THREAD

**Issue by snaper9** [pryley/site-reviews#2]
Is there a way to change the args['type'] to 'list' using a filter?

**Comment by pryley** [comment]
Hi @snaper9 

Please use the [support forum](https://wordpress.org/support/plugin/site-reviews/) for help with the plugin. Github issues are only for problems with the code.

Also, I don't completely understand your question. Please try to add additional details when you post on the forum and I'll be able to better assist you.

Thanks
