### ISSUE TITLE
Duplicate Queries wp_glsr_ratings

### ISSUE THREAD

**Issue by wpsumo** [pryley/site-reviews#25]
Duplicate Queries found with Query Monitor when using Site reviews with shortcodes with assigned posts

Query | Count | Callers | Components | Potential Troublemakers
-- | -- | -- | -- | --

<tr class=""><td class="qm-row-sql qm-ltr qm-wrap"><code><b>SELECT</b> r.rating, r.type, COUNT(r.rating) <b>AS</b> count<br> <b>FROM</b> wp_glsr_ratings <b>AS</b> r<br> <b>INNER</b> <b>JOIN</b> wp_glsr_assigned_posts <b>AS</b> apt<br> <b>ON</b> r.ID = apt.rating_id<br> <b>WHERE</b> 1=1<br> <b>AND</b> r.rating &gt; 0<br> <b>AND</b> r.is_approved = 1<br> <b>AND</b> r.type = 'local'<br> <b>AND</b> ((apt.post_id <b>IN</b> ('829')<br> <b>AND</b> apt.is_published = 1))<br> <b>GROUP</b> <b>BY</b> r.type, r.rating</code></td><td class="qm-num">2</td><td class="qm-row-caller qm-nowrap qm-ltr"><button class="qm-filter-trigger" data-qm-target="db_queries-wpdb" data-qm-filter="caller" data-qm-value="GeminiLabs\SiteReviews\Database->dbGetResults()"><code>GeminiLabs\SiteReviews\Database-&gt;dbGetResults()</code></button><br><span class="qm-info qm-supplemental">2 calls</span><br></td><td class="qm-row-component qm-nowrap">Plugin: site-reviews<br><span class="qm-info qm-supplemental">2 calls</span><br></td><td class="qm-row-caller qm-nowrap qm-ltr"><code>GeminiLabs\SiteReviews\Database-&gt;dbGetResults()</code><br><span class="qm-info qm-supplemental">2 calls</span><br></td></tr>

**Comment by pryley** [comment]
That query is only run once per shortcode. You probably have more than one summary shortcode or widget on the page.

![image](https://user-images.githubusercontent.com/134939/117864403-5eab0880-b25a-11eb-96f3-cfbf4aaa19a4.png)

![image](https://user-images.githubusercontent.com/134939/117864367-53f07380-b25a-11eb-8a97-cbfe8e5171a9.png)

**Comment by wpsumo** [comment]
@pryley You are right it's tagged the same so query monitor flag it as duplicate while it's two different short code widgets. Thanks.

There is no way it can be limited with 1 query as the same array is used just different parts for different widgets to place them differently? As I think it's commonly used like this for some users to have a more flexible design. But that comes at extra SQL queries. Just asking, the sql queries is well optimized anyhow but maybe things can still be improved. Just an idea maybe not possible to inherit and fetch the value from the other array already called and recevied.

**Comment by pryley** [comment]
All database queries used in Site Reviews are highly optimised for performance. The queries for each shortcode differ depending on the options used.

If you need further optimisation, I recommend you check out one of the many caching and performance plugins which provide database query caching.

**Comment by wpsumo** [comment]
So site reviews take full advantage of redis as object cache in wordpress? I have it enabled on the stack and in wordpress.

**Comment by pryley** [comment]
Site Reviews uses the WordPress wpdb class to make queries to the database so any caching that affects WordPress queries should apply.

**Comment by wpsumo** [comment]
Thanks, sounds great reassuring to hear.
