### ISSUE TITLE
Review details disappeared from client webiste

### ISSUE THREAD

**Issue by idt100w** [pryley/site-reviews#26]
Good morning, 

a client complained about disappearing reviews. I checked his own website and it seems that all the "Review details" are disappeared:
![deprijs01](https://user-images.githubusercontent.com/53651895/119332776-5a82e000-bc89-11eb-81f3-dffb5360597c.JPG)

He claimed that are always been visible but he doesn't know when are disappeared.
If you need it, I can provide you the full login credentials.
Could you please take a look? I can't find any solution related to this issue.

Greetings,

Matteo

**Comment by pryley** [comment]
Hi, please see: https://wordpress.org/support/topic/🚨-read-this-if-your-reviews-are-broken-after-updating-to-v5-2/
