### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by mobiliodevelopment** [pryley/site-reviews#28]
Hello there!

I have an performance issue with THIS plugin.

There is some Woocommerce site that i'm helping with migration between servers. 

Without SR plugin queries on DB measured from QM are like 40. 
With SR activated queries become 400.

And TTFB become from second to almost two seconds.

Is there an way to optimize plugin performance with something like Redis?

**Comment by pryley** [comment]
Okay first of all, you say that you are migrating between servers. Does this mean that you are experiencing problems during migration, or in general running of the website?

Site Reviews uses highly optimised SQL queries which usually take microseconds to run (profiled using [Query Monitor](https://wordpress.org/plugins/query-monitor/) and [Blackbar](https://wordpress.org/plugins/blackbar/)). The queries are specifically optimised to handle thousands of reviews without affecting performance. The [site_reviews_summary] shortcode performs 1 SQL query, the [site_reviews] shortcode runs 3 SQL queries.

The Site Reviews hooks have also been profiled for performance using the [Debug Bar Slow Actions](https://wordpress.org/plugins/debug-bar-slow-actions/) plugin.

In short, you should not be experiencing performance issues with Site Reviews...and if you are, there is likely something else at play that is contributing to the problem, or perhaps there is a compatibility issue with another plugin.

1. In Query Monitor you can sort SQL Queries by Time which will tell you which SQL Queries are slow. The Caller of the Site Reviews Queries will look something like `GeminiLabs\S\Database->dbGetResults()`. Please sort the Queries by Time in Query Monitor and post a screenshot of **Before** and **After** Site Reviews is activated.

2. Query Monitor does not profile how long hooks take to run. Slow hooks are one of the main causes for slow WordPress websites. To find out which hooks are slowing down your website, please install the [Debug Bar](https://wordpress.org/plugins/debug-bar/) and [Debug Bar Slow Actions](https://wordpress.org/plugins/debug-bar-slow-actions/). Once you have done that, you should see a "Debug" item in the admin bar with a "Slow Actions" item in the Debug menu. Please post a screenshot of the Slow Actions page **Before** and **After** Site Reviews is activated.

3. It would also help to see your Site Reviews System Info and Console Log. Please use the Contact Support section on the Help page to send it to me.

**Comment by mobiliodevelopment** [comment]
Before:

![Screen Shot 2021-09-08 at 1 58 45 AM](https://user-images.githubusercontent.com/6385295/132420935-e8a06772-692f-4d8d-a2b5-e6727f1e7bf6.png)

After:

![Screen Shot 2021-09-08 at 1 57 28 AM](https://user-images.githubusercontent.com/6385295/132420961-8e8464d7-da3d-47cc-befd-01d291c94dc9.png)

Only difference is enabling plugin.

I will sent later tomorrow system info and console log.

**Comment by pryley** [comment]
Can you expand the wp_head, wp_enqueue_scripts, the_content, and get_post_meta hooks so I can see which functions are running in each?

This definitely looks like a plugin conflict.

**Comment by pryley** [comment]
Also, is this a non-production website that I would be able to access to debug the cause?

**Comment by pryley** [comment]
@mobiliodevelopment do you have an update on this?
