### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by wpsumo** [pryley/site-reviews#3]
- Add support for reviews schema markup so it can be used to review products or brands.
- Add default support for more schema markup, creative work, and many more predefined markups.
- Add support to assign different schema markups per cpt and/or page_id or per shortcode "schema-review=true"
- Add support to only add a review from webmaster.
- Add support to change the text of the submit button.
- Add user ip or cookie restriction to allow x amount of votes/reviews per days/hours etc. 

Some feedback that would give the user more flexibility and more use cases for the plugin.

**Comment by pryley** [comment]
https://wordpress.org/support/topic/feature-requests-173/#post-11674631
